// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Session } from '@supabase/supabase-js';
import type { Database } from './types';

const rawSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_URL =
  typeof rawSupabaseUrl === 'string' ? rawSupabaseUrl.replace(/\/+$/, '') : rawSupabaseUrl;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const AUTH_STORAGE_KEY = 'paiva-cleaners-auth';
const LEGACY_AUTH_KEY = 'sb-npphcarhvobjsvdsjsyz-auth-token';
const AUTH_ERROR_EVENT = 'paiva-cleaners-auth-error';
const isBrowser = typeof window !== 'undefined';

const hasValidSupabaseEnv =
  typeof SUPABASE_URL === 'string' &&
  /^https:\/\/.+\.supabase\.co$/i.test(SUPABASE_URL) &&
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

const shouldClearAuthState = (message: string, url: string) => {
  const normalized = message.toLowerCase();
  return (
    url.includes('/auth/v1/token') ||
    normalized.includes('authretryablefetcherror') ||
    normalized.includes('failed to fetch') ||
    normalized.includes('err_name_not_resolved') ||
    normalized.includes('refresh_token') ||
    normalized.includes('lock broken') ||
    normalized.includes('was not released within') ||
    normalized.includes('invalid refresh token') ||
    normalized.includes('aborterror')
  );
};

const clearStorageKeys = (storage: Storage | undefined) => {
  if (!storage) return;

  const keysToRemove: string[] = [];
  for (let index = 0; index < storage.length; index += 1) {
    const key = storage.key(index);
    if (!key) continue;

    if (
      key === LEGACY_AUTH_KEY ||
      key === AUTH_STORAGE_KEY ||
      key === 'supabase.auth.token' ||
      key.startsWith('sb-') ||
      key.startsWith('lock:sb-')
    ) {
      keysToRemove.push(key);
    }
  }

  keysToRemove.forEach((key) => storage.removeItem(key));
};

export const clearBrokenSupabaseSession = () => {
  if (!isBrowser) return;

  clearStorageKeys(window.localStorage);
  clearStorageKeys(window.sessionStorage);
};

const notifyAuthError = (message: string) => {
  if (!isBrowser) return;

  window.dispatchEvent(new CustomEvent(AUTH_ERROR_EVENT, { detail: message }));
};

const safeFetch: typeof fetch = async (input, init) => {
  try {
    return await fetch(input, init);
  } catch (error) {
    const url =
      typeof input === 'string'
        ? input
        : input instanceof Request
          ? input.url
          : String(input);
    const message = error instanceof Error ? error.message : 'Failed to fetch';

    if (shouldClearAuthState(message, url)) {
      clearBrokenSupabaseSession();
      notifyAuthError(message);
    }

    throw error;
  }
};

if (!hasValidSupabaseEnv) {
  console.warn('[supabase] Invalid or missing Supabase environment variables. Public UI will continue with fallbacks.');
  clearBrokenSupabaseSession();
}

const storage = isBrowser ? window.localStorage : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  hasValidSupabaseEnv ? SUPABASE_URL : 'https://invalid.supabase.co',
  hasValidSupabaseEnv ? SUPABASE_PUBLISHABLE_KEY : 'invalid-key',
  {
    global: {
      fetch: safeFetch,
    },
    auth: {
      storage,
      persistSession: hasValidSupabaseEnv,
      autoRefreshToken: hasValidSupabaseEnv,
      detectSessionInUrl: true,
      storageKey: AUTH_STORAGE_KEY,
    },
  }
);

export const getAuthErrorEventName = () => AUTH_ERROR_EVENT;

export const getSafeSession = async (): Promise<Session | null> => {
  if (!hasValidSupabaseEnv) {
    return null;
  }

  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      if (shouldClearAuthState(error.message, '/auth/v1/token')) {
        clearBrokenSupabaseSession();
        notifyAuthError(error.message);
      }
      return null;
    }
    return data.session ?? null;
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to read auth session';
    if (shouldClearAuthState(message, '/auth/v1/token')) {
      clearBrokenSupabaseSession();
      notifyAuthError(message);
    }
    return null;
  }
};

export const safeSignOut = async () => {
  try {
    await supabase.auth.signOut({ scope: 'local' });
  } catch {
    // Ignore local sign-out transport failures and clear storage anyway.
  } finally {
    clearBrokenSupabaseSession();
  }
};

void getSafeSession();